apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api-stable
  labels:
    app: demo-api
    version: stable
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-api
      version: stable
  template:
    metadata:
      labels:
        app: demo-api
        version: stable
    spec:
      containers:
        - name: api
          image: blackrosse/demo-api:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
