on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    uses: katalinaino/shared-workflows/.github/workflows/deploy-api.yaml@main

    with:
      image-name: my-api
      image-tag: ${{ github.ref_name }}
      k3s-server-public-ip: ${{ vars.K3S_SERVER_PUBLIC_IP }}

    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}