on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read

jobs:
  deploy:
    uses: pacontrerasj/KBTDEL-AUY-1104--SharedWorkflowsV2/.github/workflows/deploy-api.yaml@main

    with:
      image-name: my-api
      image-tag: ${{ github.ref_name }}
      environment: prod

    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}